### ISSUE TITLE
Criação do documento de metologia

### ISSUE THREAD

**Issue by Joao-Moura** [Interacao-Humano-Computador/2021.1-Grupo01#5]
# Descrição
Criar o documento de metodologia do projeto, que ira conter as metodologias que serão utilizadas durante o processo de desenvolvimento do trabalho, bem como a política de branchs que irá ser seguida

# Tarefas

- [x]  Conter o documento de metodologia
- [x] Conter a política de branchs

**Comment by francisco1code** [comment]
Tive alguns problemas com o "ammed", então tive que mexer no historico da branch da master, mas já foi tudo resolvido. 

![](https://media.giphy.com/media/Wn74RUT0vjnoU98Hnt/giphy.gif)
